### ISSUE TITLE
With hook and route control - Re render

### ISSUE THREAD

**Issue by Pills2389** [cudr/react-modal-promise#14]
Hi, I have a problem when I use the modal with the hook and route control. It basically causes the whole page to rerender, and I think is because of the Context, because I wrap the whole application in it.

If I modify the ModalProvider component to use constate (does the same thing as Redux, but is much easier to implement) instead of react Context do you think it will prevent rerendering the whole application?

Sorry if it's a stupid question, I'm pretty new at React.

**Comment by cudr** [comment]
@Pills2389, thank for your question! Can you attach some steps for reproduce?

**Comment by cudr** [comment]
@Pills2389, this is a feature. This double re-render occurs because most of modals have their out transition. In this case root modal container forced to trigger two updates: the first one when modal closes and the second when modal unmounts. You can change unmount delay by [exitTimeout prop](https://github.com/cudr/react-modal-promise/blob/442dbda1f45209da170657feaf1ac5e9b3e7b429/src/Container.tsx#L194)
